# Generated by Django 2.2.18 on 2021-06-22 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainrelation',
            name='student',
            field=models.ManyToManyField(to='api.StudentInfo'),
        ),
    ]
