# Generated by Django 2.2.18 on 2021-05-25 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210526_0021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentinfo',
            name='grade',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='nation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Countries'),
        ),
    ]
