# Generated by Django 2.2.18 on 2021-06-23 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_messagetype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='betyear',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.StudentGrade'),
        ),
    ]
