# Generated by Django 2.2.18 on 2021-06-23 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210623_2209'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainrelation',
            name='isarranged',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='mainrelation',
            name='testroom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='testroom', to='api.ClassRoom'),
        ),
    ]
