# Generated by Django 2.2.18 on 2021-06-23 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20210623_2212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mainrelation',
            name='isarranged',
        ),
        migrations.AddField(
            model_name='course',
            name='isarranged',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='course',
            name='testtime',
            field=models.DateTimeField(null=True),
        ),
        migrations.DeleteModel(
            name='TestRelation',
        ),
    ]
