# Generated by Django 2.2.18 on 2021-05-31 00:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20210531_0827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admininfo',
            name='token',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Usertoken'),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='token',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Usertoken'),
        ),
        migrations.AlterField(
            model_name='teacherinfo',
            name='token',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Usertoken'),
        ),
    ]
