# Generated by Django 2.2.18 on 2021-05-31 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20210531_0828'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admininfo',
            name='token',
        ),
        migrations.RemoveField(
            model_name='studentinfo',
            name='token',
        ),
        migrations.RemoveField(
            model_name='teacherinfo',
            name='token',
        ),
    ]
