# Generated by Django 2.2.18 on 2021-06-26 01:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20210626_0052'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student2relation',
            old_name='mainrelation',
            new_name='relation',
        ),
    ]
