# Generated by Django 2.2.18 on 2021-05-31 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20210531_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentinfo',
            name='grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.StudentGrade'),
        ),
    ]
