# Generated by Django 2.2.18 on 2021-06-27 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_message_messagetype'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='isWatched',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='message',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
