# Generated by Django 2.2.18 on 2021-06-27 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_message_towho'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
