# Generated by Django 2.2.18 on 2021-06-27 22:08

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_delete_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fromwho', models.CharField(default='none', max_length=30)),
                ('towho', models.CharField(default='none', max_length=30)),
                ('title', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=1000, null=True)),
                ('gettime', models.DateTimeField(default=django.utils.timezone.now)),
                ('finishtime', models.DateTimeField(null=True)),
                ('isFinished', models.BooleanField(default=False)),
                ('isWatched', models.BooleanField(default=False)),
                ('result', models.CharField(default='none', max_length=30)),
                ('admin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.AdminInfo')),
                ('messagetype', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.MessageType')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.StudentInfo')),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.TeacherInfo')),
            ],
            options={
                'ordering': ['-isFinished', ['-gettime'], ['-finishtie']],
            },
        ),
    ]
