# Generated by Django 2.2.18 on 2021-06-07 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20210605_1452'),
    ]

    operations = [
        migrations.CreateModel(
            name='Betteryear',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
            ],
        ),
    ]
