# Generated by Django 2.2.18 on 2021-06-07 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_betteryear'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='pre_course',
        ),
        migrations.AddField(
            model_name='course',
            name='pre_course',
            field=models.ManyToManyField(null=True, related_name='_course_pre_course_+', to='api.Course'),
        ),
    ]
