# Generated by Django 2.2.18 on 2021-06-27 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_message'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-isFinished', ['-gettime'], ['-finishtime']]},
        ),
    ]
