# Generated by Django 2.2.18 on 2021-06-28 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20210627_2250'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='reply',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
