# Generated by Django 2.2.18 on 2021-06-29 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_message_reply'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-isFinished', '-gettime', '-finishtime']},
        ),
    ]
