# Generated by Django 2.2.18 on 2021-06-09 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_auto_20210608_0013'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainRelation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.ClassRoom')),
                ('classtime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.ClassTime')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Course')),
                ('student', models.ManyToManyField(to='api.StudentInfo')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.TeacherInfo')),
            ],
        ),
    ]
