# Generated by Django 2.2.18 on 2021-06-29 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_auto_20210629_0419'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['isFinished', '-gettime', '-finishtime']},
        ),
    ]
