# Generated by Django 2.2.18 on 2021-06-18 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_auto_20210610_1634'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mainrelation',
            name='classtime',
        ),
        migrations.AddField(
            model_name='mainrelation',
            name='classtime',
            field=models.ManyToManyField(to='api.ClassTime'),
        ),
    ]
