# Generated by Django 2.2.18 on 2021-06-18 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_auto_20210618_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainrelation',
            name='stuquantity',
            field=models.IntegerField(default=0),
        ),
    ]
