from django.contrib import admin
from django.urls import path , include , re_path
from api.views.admin import course,student,room,teacher,course,college,schedule
from api.views import general
from api import teacherurls,studenturls

urlpatterns = [
    path('teacher/',include(teacherurls)),
    path('student/',include(studenturls)),
    path('login/',general.login.as_view()),
    path('studentlist/',student.studentStatus.as_view()),
    path('studentinfo/',student.studentInfo.as_view()),
    path('editstuoptions/',student.editstuoptions.as_view()),
    path('getlocation/',student.getlocation.as_view()),
    path('getclass/',student.getclass.as_view()),
    path('editstudent/',student.editstudent.as_view()),
    path('getOrganize/',student.getOrganize.as_view()),
    path('addstudent/',student.addStudent.as_view()),
    path('deletestudent/',student.deleteStudent.as_view()),
    path('roomlist/',room.roomList.as_view()),
    path('getfunctions/',room.getFunctions.as_view()),
    path('getroominfo/',room.getRoomInfo.as_view()),
    path('filterroom/',room.filterRoom.as_view()),
    path('getteacher/',teacher.getTeacherlist.as_view()),
    path('getteacherinfo/',teacher.getTeacherinfo.as_view()),
    path('editteaoptions/',teacher.editTeacherOptions.as_view()),
    path('editteacher/',teacher.editTeacher.as_view()),
    path('addteacher/',teacher.addTeacher.as_view()),
    path('collegechange/',teacher.collegeChange.as_view()),
    path('getcourselist/',course.getCourseList.as_view()),
    path('filtercourselist/',course.filterCourseList.as_view()),
    path('initcourseinfo/',course.initCourseInfo.as_view()),
    path('getcourseoption/',course.getCourseOption.as_view()),
    path('submitcourse/',course.submitCourse.as_view()),
    path('addcourse/',course.addCourse.as_view()),
    path('deletecourse/',course.deleteCourse.as_view()),
    path('getcolleges/',college.getColleges.as_view()),
    path('getmajors/',college.getMajors.as_view()),
    path('getclasses/',college.getClasses.as_view()),
    path('initmajorinfo/',college.initMajorInfo.as_view()),
    path('editmajoroptions/',college.editMajorOptions.as_view()),
    path('postmajorsubmit/',college.postMajorSubmit.as_view()),
    path('getscheduled/',schedule.getScheduled.as_view()),
    path('getvalidroom/',schedule.getValidRoom.as_view()),
    path('getcolcou/',schedule.getColCou.as_view()),
    path('getschbuilding/',schedule.getSchBuilding.as_view()),
    path('addschedule/',schedule.addSchedule.as_view()),
    path('getcoursesch/',schedule.getCourseSch.as_view()),
]