# Generated by Django 2.2.18 on 2021-05-24 02:22

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('adm_id', models.CharField(default='', max_length=20, unique=True)),
                ('password', models.CharField(default='123456', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Areas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aid', models.IntegerField(default=0)),
                ('atitle', models.CharField(max_length=30)),
                ('aParent', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('direct', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Cities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aid', models.IntegerField(default=0)),
                ('atitle', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='ClassInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('class_id', models.CharField(default='', max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClassRoom',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=10, unique=True)),
                ('capacity', models.IntegerField()),
                ('building', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.Building')),
            ],
        ),
        migrations.CreateModel(
            name='ClassTime',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='CollegeInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('college_id', models.IntegerField(unique=True)),
                ('name', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='CollegeInfo4tc',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('college_id', models.IntegerField(unique=True)),
                ('name', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Countries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aid', models.IntegerField(default=0)),
                ('atitle', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cou_id', models.CharField(default='', max_length=10, unique=True)),
                ('name', models.CharField(default='', max_length=10, unique=True)),
                ('classhour', models.IntegerField()),
                ('hourperweek', models.FloatField(default=1.0)),
                ('credit', models.FloatField()),
                ('betyear', models.IntegerField()),
                ('elective', models.BooleanField(default=False)),
                ('priority', models.IntegerField(default=1)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.CollegeInfo4tc')),
            ],
        ),
        migrations.CreateModel(
            name='Function',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='ordinary', max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='IDNumber',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('idnumber', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Outlook',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Student2Course',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('isfinished', models.BooleanField(default=False)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher_title',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='TeacherInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tea_id', models.CharField(default='', max_length=20, unique=True)),
                ('password', models.CharField(default='123456', max_length=50)),
                ('name', models.CharField(default='', max_length=20)),
                ('birthday', models.DateField(default=django.utils.timezone.now)),
                ('sex', models.CharField(default='', max_length=5)),
                ('entryTime', models.DateField(auto_now_add=True)),
                ('nation', models.IntegerField(default=0)),
                ('IDnumber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.IDNumber')),
                ('college', models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='api.CollegeInfo4tc')),
                ('course', models.ManyToManyField(to='api.Course')),
                ('native', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Cities')),
                ('outlook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Outlook')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Teacher_title')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher2Time',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.ClassRoom')),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Course')),
                ('teacher_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.TeacherInfo')),
                ('time_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.ClassTime')),
            ],
        ),
        migrations.CreateModel(
            name='StudentInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('stu_id', models.CharField(default='', max_length=20, unique=True)),
                ('password', models.CharField(default='123456', max_length=50)),
                ('name', models.CharField(default='', max_length=20)),
                ('birthday', models.DateField(default=django.utils.timezone.now)),
                ('sex', models.CharField(default='', max_length=5)),
                ('entryTime', models.DateField(default=django.utils.timezone.now)),
                ('grade', models.IntegerField()),
                ('nation', models.IntegerField(default=0)),
                ('credit', models.FloatField(default=0)),
                ('Class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.ClassInfo')),
                ('IDnumber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.IDNumber')),
                ('elecourse', models.ManyToManyField(through='api.Student2Course', to='api.Course')),
                ('native', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Cities')),
                ('outlook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Outlook')),
            ],
        ),
        migrations.AddField(
            model_name='student2course',
            name='student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.StudentInfo'),
        ),
        migrations.CreateModel(
            name='Results',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('result', models.IntegerField()),
                ('examtime', models.DateField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.StudentInfo')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.TeacherInfo')),
            ],
        ),
        migrations.CreateModel(
            name='Provinces',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aid', models.IntegerField(default=0)),
                ('atitle', models.CharField(max_length=30)),
                ('Country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Countries')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fromwho', models.CharField(default='none', max_length=30)),
                ('title', models.CharField(max_length=50)),
                ('content', models.CharField(max_length=1000, null=True)),
                ('gettime', models.DateTimeField(default=django.utils.timezone.now)),
                ('finishtime', models.DateTimeField(default=django.utils.timezone.now)),
                ('isFinished', models.IntegerField(default=0)),
                ('result', models.CharField(default='none', max_length=30)),
                ('admin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.AdminInfo')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.StudentInfo')),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.TeacherInfo')),
            ],
            options={
                'ordering': ['-isFinished', ['-gettime'], ['-finishtie']],
            },
        ),
        migrations.CreateModel(
            name='MajorInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('major_id', models.IntegerField()),
                ('name', models.CharField(default='', max_length=20)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.CollegeInfo')),
                ('course', models.ManyToManyField(to='api.Course')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='function',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.Function'),
        ),
        migrations.AddField(
            model_name='course',
            name='pre_course',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Course'),
        ),
        migrations.AddField(
            model_name='classroom',
            name='function',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.Function'),
        ),
        migrations.AddField(
            model_name='classinfo',
            name='major',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.MajorInfo'),
        ),
        migrations.AddField(
            model_name='cities',
            name='Province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Provinces'),
        ),
    ]
