# Generated by Django 2.2.18 on 2021-06-03 06:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20210531_1752'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentinfo',
            name='College',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.CollegeInfo'),
        ),
        migrations.AddField(
            model_name='studentinfo',
            name='Major',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.MajorInfo'),
        ),
    ]
