# Generated by Django 2.2.18 on 2021-06-03 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20210603_1405'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentinfo',
            old_name='native',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='studentinfo',
            old_name='nation',
            new_name='country',
        ),
        migrations.AddField(
            model_name='studentinfo',
            name='province',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.Provinces'),
        ),
    ]
