# Generated by Django 2.2.18 on 2021-06-05 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20210604_0006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacherinfo',
            name='nation',
        ),
        migrations.RemoveField(
            model_name='teacherinfo',
            name='native',
        ),
        migrations.AddField(
            model_name='teacherinfo',
            name='city',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.Cities'),
        ),
        migrations.AddField(
            model_name='teacherinfo',
            name='country',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.Countries'),
        ),
        migrations.AddField(
            model_name='teacherinfo',
            name='province',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.Provinces'),
        ),
    ]
