# Generated by Django 2.2.18 on 2021-06-07 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20210608_0012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='pre_course',
            field=models.ManyToManyField(related_name='_course_pre_course_+', to='api.Course'),
        ),
    ]
