# Generated by Django 2.2.18 on 2021-06-09 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_mainrelation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(default='', max_length=100, unique=True),
        ),
    ]
