# Generated by Django 2.2.18 on 2021-06-10 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_auto_20210609_2332'),
    ]

    operations = [
        migrations.CreateModel(
            name='Days',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='classtime',
            name='Days',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Days'),
        ),
    ]
